### ISSUE TITLE
Hey, this is great but

### ISSUE THREAD

**Issue by bharal** [malcolmgreaves/auto-gfqg#5]
Hi, this project looks really interesting - but!

When i run it - "run" i get prompted for 9 items. If i just wanted to try this out - ie i have a block of text, i'd like to see the questions/answers produced - what do i have to do?

Also, when i select a number at the screen i get an error (note all i do is hit "1" and then "enter", i don't provide any other input):

```
Multiple main classes detected, select one to run:

 [1] agfqg.ConllToTextLine
 [2] agfqg.CreateTopicWordVecs
 [3] agfqg.FinalQuizQuestionsJson
 [4] agfqg.GapWordAndDistractorSelection
 [5] agfqg.NlpAwareGapWordAndDistractorSelection
 [6] agfqg.ScoreSentences
 [7] agfqg.SelectSentencesForQuestions
 [8] agfqg.VocabFilterGapWordAndDistractorSelection
 [9] edu.stanford.nlp.process.Stemmer
^JEnter number: 1

[info] Running agfqg.ConllToTextLine
[HELP] Need 2 arguments:
1st: INPUT processed text, in CoNLL format
2nd: OUTPUT plain text, each line is a complete sentence


Exception: sbt.TrapExitSecurityException thrown from the UncaughtExceptionHandler in thread "run-main-0"
java.lang.RuntimeException: Nonzero exit code: 1
        at scala.sys.package$.error(package.scala:27)
[trace] Stack trace suppressed: run last compile:run for the full output.
[error] (compile:run) Nonzero exit code: 1
[error] Total time: 8 s, completed Nov 7, 2018 11:58:45 PM
```

**Comment by malcolmgreaves** [comment]
Hello! Thanks for your interest in the project.

First, please read through all of the documentation. I wrote it so that one could completely understand how all pieces of this project work. The documentation serves as both education for what the project does as well as a reference for how to use the code. The project's `README` is where to start. Specifically this section: https://github.com/malcolmgreaves/auto-gfqg#overview-of-information-flow

Second, there is not one single program in this project (as you have found out :D). The small, modular programs participate to form a processing pipeline. Importantly, all of these programs accept data as input and produce data as output: none of them are able to run without also supplying I/O.

If you read through the documentation, you'll see that these programs must be run in a specific sequential order.

For instance, the program you referenced, `agfqg.ConllToTextLine`, tells you that you need to supply two filepaths. The first is to a file containing tokenized text in the CoNLL 2003 format. The second is where the program will write its output. This is precisely what the program is telling you right underneath the `[HELP] Need 2 arguments:` line.

Happy hacking :D
